-- ============================================================================
-- RSVP app — Phase 2 data model
-- ============================================================================
-- Run this once in your Supabase project's SQL Editor (Dashboard → SQL Editor
-- → New query → paste this whole file → Run). Safe to re-run only after
-- dropping the tables first; it does not use "create table if not exists"
-- on purpose, so you notice if something already exists.
--
-- Entities: admin_profile, events, rsvps, categories, category_slots, signups
-- ============================================================================

-- Needed for gen_random_uuid()
create extension if not exists pgcrypto;

-- ----------------------------------------------------------------------------
-- admin_profile
-- One row per admin (Supabase Auth user). Cass logs in through Supabase Auth
-- (email/password); this table just holds the coordinator info that would
-- otherwise have to be re-typed on every event (name, contact info).
-- ----------------------------------------------------------------------------
create table admin_profile (
  id uuid primary key references auth.users (id) on delete cascade,
  display_name text not null default '',
  contact_email text,
  contact_phone text,
  organization_name text,
  updated_at timestamptz not null default now()
);

-- ----------------------------------------------------------------------------
-- events
-- ----------------------------------------------------------------------------
create table events (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  event_date date not null,
  start_time time,
  end_time time,
  location_name text,
  address text,
  notes text,

  -- Path inside the 'flyers' storage bucket, e.g. "<event_id>/flyer.jpg".
  -- Null means "no flyer uploaded" — the public page falls back to the
  -- default community logo bundled in the React app, not a database value.
  flyer_path text,

  -- draft: not visible publicly. open: visible + RSVPs accepted.
  -- closed: visible, but new RSVPs blocked (edit links may still work,
  -- see edit_links_disabled_on_close).
  status text not null default 'draft'
    check (status in ('draft', 'open', 'closed')),

  -- Optional automatic close time. Enforced by the app (Supabase doesn't
  -- run cron-on-read), so treat "closed" (the status column) as the source
  -- of truth once the app has acted on a passed deadline.
  rsvp_deadline timestamptz,

  -- Whether a resident's optional comment is shown next to their name in
  -- the public "Who's Coming" list.
  show_comments_publicly boolean not null default false,

  -- If true, existing edit links stop working once the event is closed.
  edit_links_disabled_on_close boolean not null default false,

  created_by uuid references auth.users (id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index events_status_idx on events (status);
create index events_event_date_idx on events (event_date);

-- ----------------------------------------------------------------------------
-- rsvps
-- One row per resident's MAIN rsvp to an event (Going / Not Going).
-- Duplicate-name protection lives here via the unique constraint on
-- (event_id, name_normalized) — "Violet Rein", "violet rein", and
-- "Violet  Rein" all normalize to the same value and collide on insert.
-- ----------------------------------------------------------------------------
create table rsvps (
  id uuid primary key default gen_random_uuid(),
  event_id uuid not null references events (id) on delete cascade,

  name text not null,
  -- lower(trim(name)) with internal whitespace collapsed to single spaces.
  -- Computed and written by the application, not the database, so the
  -- normalization rule stays in one place (see Phase 4 duplicate-checking).
  name_normalized text not null,

  status text not null default 'going'
    check (status in ('going', 'not_going')),
  comment text,

  -- Long, random, unguessable token used in the /edit-rsvp/:token URL.
  -- Never a sequential id. Generated by the app with a CSPRNG (e.g.
  -- crypto.randomUUID() or a 32-byte random hex string) at insert time.
  edit_token text not null unique,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  unique (event_id, name_normalized)
);

create index rsvps_event_id_idx on rsvps (event_id);
create index rsvps_edit_token_idx on rsvps (edit_token);

-- ----------------------------------------------------------------------------
-- categories
-- ----------------------------------------------------------------------------
create table categories (
  id uuid primary key default gen_random_uuid(),
  event_id uuid not null references events (id) on delete cascade,

  name text not null,
  description text,

  -- open_contribution: residents freely describe what they're bringing
  --   (e.g. "Salads & Sides" — "Orzo Salad").
  -- specific_slot: Cass predefines named slots with a quantity needed
  --   (e.g. "Plates — 3 needed"); tracked via category_slots.
  -- volunteer_donation: same-person duplicate participation is allowed
  --   (a resident can volunteer for multiple assignments).
  category_type text not null
    check (category_type in ('open_contribution', 'specific_slot', 'volunteer_donation')),

  -- Used by open_contribution categories as the overall cap on
  -- contributors. Ignored for specific_slot (each slot has its own
  -- quantity_needed) and typically left null (unlimited) for
  -- volunteer_donation.
  max_signups integer,

  active boolean not null default true,
  sort_order integer not null default 0,

  created_at timestamptz not null default now()
);

create index categories_event_id_idx on categories (event_id);

-- ----------------------------------------------------------------------------
-- category_slots
-- Only populated for specific_slot and volunteer_donation categories.
-- Examples: "Plates" (quantity_needed 3), "Ice" (quantity_needed 4),
-- "Waffle Station Volunteer" (quantity_needed null = unlimited).
-- ----------------------------------------------------------------------------
create table category_slots (
  id uuid primary key default gen_random_uuid(),
  category_id uuid not null references categories (id) on delete cascade,

  name text not null,
  quantity_needed integer, -- null = unlimited
  instructions text,
  sort_order integer not null default 0,

  created_at timestamptz not null default now()
);

create index category_slots_category_id_idx on category_slots (category_id);

-- ----------------------------------------------------------------------------
-- signups
-- A single "what I'm bringing" / "I'll do this slot" / "I'm
-- volunteering/donating" entry. Always tied back to an rsvp_id so it can
-- be managed from that resident's edit-link page — residents never need a
-- second account to sign up for a category.
-- ----------------------------------------------------------------------------
create table signups (
  id uuid primary key default gen_random_uuid(),
  category_id uuid not null references categories (id) on delete cascade,

  -- Set for specific_slot / volunteer_donation signups; null for
  -- open_contribution signups (those just use item_description).
  slot_id uuid references category_slots (id) on delete cascade,

  rsvp_id uuid not null references rsvps (id) on delete cascade,

  -- Denormalized so the public category page can render names without a
  -- join back through rsvps, and so a name still displays correctly even
  -- if the resident later edits their main RSVP name.
  contributor_name text not null,
  contributor_name_normalized text not null,

  -- Free text for open_contribution ("Orzo Salad") or an optional note on
  -- a slot/volunteer signup.
  item_description text,

  created_at timestamptz not null default now()
);

create index signups_category_id_idx on signups (category_id);
create index signups_slot_id_idx on signups (slot_id);
create index signups_rsvp_id_idx on signups (rsvp_id);

-- ============================================================================
-- Row Level Security
-- ============================================================================
-- Locked down by default. Public (anon) access is limited to what the
-- public pages actually need; everything else requires an authenticated
-- admin session. Some public actions (creating an RSVP, editing one by
-- token) are deliberately NOT opened up here as broad table policies —
-- they'll be implemented as narrow Postgres functions (RPCs) in Phase 4,
-- so an anonymous visitor can never select/update rows they shouldn't be
-- able to just because they can see the table.
-- ----------------------------------------------------------------------------

alter table admin_profile enable row level security;
alter table events enable row level security;
alter table rsvps enable row level security;
alter table categories enable row level security;
alter table category_slots enable row level security;
alter table signups enable row level security;

-- admin_profile: only the admin can see/edit their own row.
create policy "admin can manage own profile"
  on admin_profile for all
  using (auth.uid() = id)
  with check (auth.uid() = id);

-- events: public can read non-draft events; admin can do everything.
create policy "public can read published events"
  on events for select
  using (status in ('open', 'closed'));

create policy "admin has full access to events"
  on events for all
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');

-- rsvps: no direct public read/write on the base table (it holds
-- edit_token, which must never be exposed in a public list). The public
-- "Who's Coming" list will read through a view instead (see below).
-- Admin has full access.
create policy "admin has full access to rsvps"
  on rsvps for all
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');

-- categories / category_slots: public can read active categories/slots on
-- published events; admin has full access.
create policy "public can read active categories"
  on categories for select
  using (
    active = true
    and exists (
      select 1 from events
      where events.id = categories.event_id
        and events.status in ('open', 'closed')
    )
  );

create policy "admin has full access to categories"
  on categories for all
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');

create policy "public can read category slots"
  on category_slots for select
  using (
    exists (
      select 1 from categories
      join events on events.id = categories.event_id
      where categories.id = category_slots.category_id
        and categories.active = true
        and events.status in ('open', 'closed')
    )
  );

create policy "admin has full access to category slots"
  on category_slots for all
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');

-- signups: public can read (so counts and contributor lists work), but
-- writes go through Phase 4/5's RPC functions, not direct inserts, so the
-- app can enforce dedupe rules and re-check capacity atomically.
create policy "public can read signups"
  on signups for select
  using (true);

create policy "admin has full access to signups"
  on signups for all
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');

-- ----------------------------------------------------------------------------
-- Public view of RSVPs — what the "Who's Coming" list is actually allowed
-- to read. Excludes name_normalized and edit_token entirely.
-- ----------------------------------------------------------------------------
create view rsvps_public as
  select id, event_id, name, comment, status, created_at
  from rsvps
  where status = 'going';

grant select on rsvps_public to anon, authenticated;

-- ============================================================================
-- Done. Next: create a Storage bucket named "flyers" (Dashboard → Storage →
-- New bucket → public) for event flyer images — see README.md for the full
-- Phase 2 setup steps.
-- ============================================================================
